// Generated by CoffeeScript 1.6.2
(function() {
  var Buffer, ChatBuffer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Buffer = require('./buffer');

  ChatBuffer = (function(_super) {
    __extends(ChatBuffer, _super);

    function ChatBuffer(connection, info) {
      ChatBuffer.__super__.constructor.call(this, connection, info);
      this.isArchived = !!info.archived;
    }

    ChatBuffer.prototype.archive = function(callback) {
      var _this = this;

      if (this.isArchived) {
        return callback();
      }
      return this.connection.engine.db.setBufferArchived(this.connection.id, this.id, true, function() {
        _this.isArchived = true;
        return _this.connection.user.broadcast({
          type: 'buffer_archived',
          cid: _this.connection.id,
          bid: _this.id
        }, callback);
      });
    };

    ChatBuffer.prototype.unarchive = function(callback) {
      var _this = this;

      if (!this.isArchived) {
        return callback();
      }
      return this.connection.engine.db.setBufferArchived(this.connection.id, this.id, false, function() {
        _this.isArchived = false;
        return _this.connection.user.broadcast({
          type: 'buffer_unarchived',
          cid: _this.connection.id,
          bid: _this.id
        }, callback);
      });
    };

    ChatBuffer.prototype["delete"] = function(callback) {
      var _this = this;

      if (this.isJoined) {
        return callback();
      }
      return this.connection.engine.db.deleteBuffer(this.connection.id, this.id, function() {
        return _this.connection.removeBuffer(_this, callback);
      });
    };

    return ChatBuffer;

  })(Buffer);

  module.exports = ChatBuffer;

}).call(this);
