// Generated by CoffeeScript 1.4.0
(function() {
  var Buffer, ConsoleBuffer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Buffer = require('./buffer');

  ConsoleBuffer = (function(_super) {

    __extends(ConsoleBuffer, _super);

    function ConsoleBuffer() {
      return ConsoleBuffer.__super__.constructor.apply(this, arguments);
    }

    ConsoleBuffer.prototype.type = 'console';

    return ConsoleBuffer;

  })(Buffer);

  module.exports = ConsoleBuffer;

}).call(this);
