// Generated by CoffeeScript 1.7.1
(function() {
  var ChatBuffer, ConversationBuffer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ChatBuffer = require('./chat_buffer');

  ConversationBuffer = (function(_super) {
    __extends(ConversationBuffer, _super);

    function ConversationBuffer() {
      return ConversationBuffer.__super__.constructor.apply(this, arguments);
    }

    ConversationBuffer.prototype.type = 'conversation';

    return ConversationBuffer;

  })(ChatBuffer);

  module.exports = ConversationBuffer;

}).call(this);

//# sourceMappingURL=conversation_buffer.map
