// Generated by CoffeeScript 1.6.3
(function() {
  var Winston, log;

  Winston = require('winston');

  log = new Winston.Logger({
    transports: [
      new Winston.transports.Console({
        timestamp: true,
        level: 'info'
      })
    ]
  });

  log.setLevel = function(level) {
    var name, transport, _ref, _results;
    this.level = level;
    _ref = this.transports;
    _results = [];
    for (name in _ref) {
      transport = _ref[name];
      _results.push(transport.level = level);
    }
    return _results;
  };

  module.exports = log;

}).call(this);

/*
//@ sourceMappingURL=log.map
*/
