// Generated by CoffeeScript 1.3.3
(function() {
  var Fs, SessionStore;

  Fs = require('fs');

  SessionStore = (function() {

    function SessionStore(fileName) {
      this.fileName = fileName;
      if (Fs.existsSync(this.fileName)) {
        this.sessions = JSON.parse(Fs.readFileSync(this.fileName).toString());
      } else {
        this.sessions = {};
      }
    }

    SessionStore.prototype.get = function(sessionId) {
      return this.sessions[sessionId];
    };

    SessionStore.prototype.set = function(sessionId, session) {
      this.sessions[sessionId] = session;
      this.save();
      return session;
    };

    SessionStore.prototype.destroy = function(sessionId) {
      delete this.sessions[sessionId];
      return this.save();
    };

    SessionStore.prototype.save = function() {
      return Fs.writeFileSync(this.fileName, JSON.stringify(this.sessions));
    };

    return SessionStore;

  })();

  module.exports = SessionStore;

}).call(this);
